global:
    scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
        - 10.1.1.7:9090 # lxcm01

  - job_name: node-exporter
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
        - 10.1.1.7:9100 # lxcm01
